# Generated by Django 4.2.9 on 2024-01-10 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Popmatches',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_team', models.CharField(max_length=25)),
                ('second_team', models.CharField(max_length=25)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('win_team', models.CharField(max_length=25)),
                ('result', models.CharField(max_length=5)),
                ('video', models.CharField(max_length=255)),
            ],
        ),
    ]
