# Generated by Django 4.2.9 on 2024-01-10 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('popmatches', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='popmatches',
            name='time',
        ),
    ]
