# Generated by Django 4.2.9 on 2024-01-10 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('popmatches', '0002_remove_popmatches_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='popmatches',
            name='time',
            field=models.IntegerField(default=30),
        ),
    ]
