# Generated by Django 4.2.9 on 2024-01-10 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('popmatches', '0003_popmatches_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='popmatches',
            name='time',
            field=models.FloatField(default=30),
        ),
    ]
