# Generated by Django 4.2.9 on 2024-01-03 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Heroes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_name', models.CharField(max_length=256, unique=True)),
                ('release_date', models.DateField()),
                ('description', models.TextField(max_length=500)),
                ('origin', models.CharField(max_length=256)),
                ('role', models.CharField(max_length=4)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.items')),
            ],
        ),
    ]
