# Generated by Django 4.2.9 on 2024-01-14 17:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_alter_news_title'),
        ('com', '0004_alter_comment_news'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='news',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='com', to='news.news', to_field='title'),
        ),
    ]
