# Generated by Django 4.2.9 on 2024-01-03 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=35)),
                ('date', models.DateField()),
                ('text', models.TextField(max_length=1500)),
            ],
        ),
    ]
