# Generated by Django 4.2.9 on 2024-01-14 19:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team1', models.CharField(max_length=20)),
                ('team2', models.CharField(max_length=20)),
                ('start_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Bet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_team', models.CharField(max_length=20)),
                ('points', models.FloatField(default=0.0)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bets.match')),
            ],
        ),
    ]
